cifs:
    image: ahri/cifs:0.0.4

    ports:
        - "139:139"
        - "445:445"

    restart: always

    volumes:
        - /mnt/media:/mnt/media

    command: nobody nogroup playtime optitron /mnt/media:share:rw
