cifs:
    image: ahri/cifs:0.0.5

    ports:
        - "139:139"
        - "445:445"

    restart: always

    volumes:
        - /mnt/media:/mnt/media

    command: 65534 65534 playtime optitron /mnt/media:share:rw
